
name: lifestyle_engagement_app
description: Lifestyle & Engagement app (Flutter web + Supabase)
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  supabase_flutter: ^1.3.0
  uuid: ^3.0.7
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
